### ISSUE TITLE
"mask borrowed" flag getting set without borrowing mask?

### ISSUE THREAD

**Issue by briaguya-ai** [HarbourMasters/rando-issue-tracker#102]
TheWaveWarden on disc reported the mask shop being broken for them

![image](https://user-images.githubusercontent.com/70942617/177399034-acda1ada-e170-4645-b698-af3ea2963dc8.png)

after looking at their save file, it seems somehow the flag for having borrowed the keaton mask got set without them having the mask

it's not clear where this got set, but the check is in `z_en_ossan.c`
```c
// Haven't borrowed the Keaton Mask
if (!(gSaveContext.itemGetInf[2] & 0x8)) {
    return 0x70A1;
}
```

**Comment by aMannus** [comment]
Could this have to do with the oversight of the happy mask shop opening too early, the player getting a mask first and then getting Zeldas letter?
