### ISSUE TITLE
Item Tracker: Song colors don't match colors in overworld/item get

### ISSUE THREAD

**Issue by briaguya-ai** [HarbourMasters/rando-issue-tracker#143]
right now the non warp songs are all white in the tracker, it'd be cool if they were colors like the note items in the overworld

**Comment by briaguya-ai** [comment]
while we're at it we should update the colors in the save editor

**Comment by aMannus** [comment]
https://cdn.discordapp.com/attachments/988962246585634856/990598117336420472/SoH_Song_Colors_V2.png

This is what the normal song colors are based on for the ingame models. Warp songs are still using the models that were already (unused) in vanilla OoT.

**Comment by briaguya-ai** [comment]
relevant PR (from when song colors were added to the models) https://github.com/briaguya-ai/Shipwright/pull/203

**Comment by briaguya-ai** [comment]
fixed with https://github.com/briaguya-ai/Shipwright/pull/336
