### ISSUE TITLE
fun junk hint ideas

### ISSUE THREAD

**Issue by briaguya-ai** [HarbourMasters/rando-issue-tracker#27]
post them here

**Comment by briaguya-ai** [comment]
in reference to my habit of using `blarg` as a temporary name for variables and value for strings

![image](https://user-images.githubusercontent.com/70942617/176355936-dd838409-15ad-431b-b5f4-7abdf467070d.png)

![image](https://user-images.githubusercontent.com/70942617/176355950-fb6f7e49-8411-49ce-a299-82fba672aa0c.png)

**Comment by InfoManiac742** [comment]
They say that if you set your audio to "Headphones", something terrible will happen...

**Comment by stratomaster64** [comment]
I have a few:

> `Join me, <player_name>, and I shall make your face the greatest in all of Koridai!...or else you will die.`
> `They say that Deku scrubs actually have nut allergies.`
> `You have no new messages.`
> `I couldn't hear what they said, sorry.`
> `They say that this peace is what all true warriors strive for.`
> `They say that if you call Saria at 3AM, something bad will happen...`

If at least one of them gets in I'll be happy.

**Comment by briaguya-ai** [comment]
@stratomaster64 added one in https://github.com/briaguya-ai/Shipwright/pull/224

![image](https://user-images.githubusercontent.com/70942617/176361669-bee5427f-5eb4-4e92-896a-d4941b88c061.png)

**Comment by Feonyx0** [comment]
If it's not already in there I saw "Link we've been trying to reach you about your car's extended warranty" I also think something like "my friend told me that gossip stones tell hints by gossiping"

**Comment by aMannus** [comment]
I used to be an adventurer like you..

They say [playername] needs to git gud

**Comment by briaguya-ai** [comment]
```
They say BOINNG!
```
early stages of a joke about link hitting them with swords, ideas for the next part i had are
`Why do you keep hitting them/us with your sword?" or something like
```
They say BOINNG! means "I am in great pain, please help me" in the gossip stone's people's tongue
```
or something

idk yet but i'm sure we'll think of something

**Comment by PurpleHato** [comment]
```
They say this Ship is what all true Gamers strive for
```
```
They say that Jack Walker isn't actually a walker
```
```
They say that Kenix is just the dude who's making Pull Request
```
```
They say that MelonSpeedruns speaks a strange dialect of French
```
```
They say that Baoulettes have an RGB addiction
```
```
They say that Lywx like to say UwU```
```
```
They say that Purple Hato will stream Xenosaga at the beginning of July
```
```
They say that Morshu can't give credit and you need to come back when you're a little hmmmm richer
```
```
They say that KCNecro playtested this randomizer
```

**Comment by briaguya-ai** [comment]
`they say that [green text]kenix[/green text] is not a developer`

**Comment by Seranim1** [comment]
In the german n64 version one gossip stone says "if you press the oval button on your console something cool will happen."

I want one gossip stone to say "if you press CTRL+R something cool will happen"

**Comment by briaguya-ai** [comment]
`They say that Glowsticks can be found in the Raveyard.`

`On peut trouver des bâtons lumineux sur le dancefloor du cimetière`

**Comment by briaguya-ai** [comment]
closing this issue, we should find a better place to gather these ideas and occasionally make a PR with new fun hints
